### ISSUE TITLE
Add ForEachField function

### ISSUE THREAD

**Issue by DasPoet** [lukasl-dev/gotilities#1]
Implement a function

```go
ForEachField(v interface{}, ignoreUnexported bool, fieldFn func(field reflect.StructField)) error
```

that calls `fieldFn` on each field of `v`, depending on `ignoreUnexported`.
`ForEachField` should return an error if `v` is not a struct.

**Comment by lukasl-dev** [comment]
Added in [v0.0.5](https://github.com/lukasl-dev/gotilities/releases/tag/v0.0.5).
